name: QALIPSIS Scenarios build, execution and packaging

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        java: ['11']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Build
        run: ./gradlew clean build

      - name: Execute the E2E test
        run: ./gradlew qalipsisRunAllScenarios

      - name: Package the scenarios
        run: ./gradlew distZip
